#!/bin/sh -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

. $SCRD/genome &&

. $SCRD/toolchain/variables &&
. $TSCR/check &&
. $TSCR/prepare &&

$SCRD/log $TLOG $TSCR/construct &&

. $TSCR/backup
