#!/usr/bin/dash -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

. $SCRD/toolchain/variables &&
. $TSCR/prepare &&

. $TSCR/cross/run &&
. $TSCR/native/run &&

. $TSCR/backup
