#!/bin/sh -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

CHOWN="chown -R" &&
LN="ln -fns" &&
MKDIR="install -d" &&
RM="rm -fr" &&
RSYNC="rsync -aHAXx" &&
UMOUNT="umount -fqR" &&

NAME=glaucus.img &&
SIZE=256M &&
LOOP=$(losetup -f) &&

$RM $NAME &&
qemu-img create -f raw $NAME $SIZE &&
dd if=scripts/other/mbr.bin of=$NAME conv=notrunc bs=440 count=1 &&

parted -s $NAME mklabel msdos &&
parted -s -a none $NAME mkpart primary ext4 0 $SIZE &&
parted -s -a none $NAME set 1 boot on &&

losetup -D &&
losetup $LOOP $NAME &&

partx -a $LOOP &&
mkfs.ext4 $(printf $LOOP)p1 &&

mount $(printf $LOOP)p1 /mnt/loop &&

$RM /mnt/loop/lost+found &&

$MKDIR /mnt/loop/dev &&
$MKDIR /mnt/loop/proc &&
$MKDIR /mnt/loop/run &&
$MKDIR /mnt/loop/sys &&

$MKDIR -m 0750 /mnt/loop/root &&
$MKDIR -m 1777 /mnt/loop/tmp &&

$RSYNC cross/boot /mnt/loop &&
$RSYNC cross/etc /mnt/loop &&
$RSYNC cross/usr /mnt/loop &&
$RSYNC cross/var /mnt/loop &&

$LN usr/bin /mnt/loop/bin &&
$LN usr/lib /mnt/loop/lib &&

$MKDIR /mnt/loop/boot/extlinux &&
$RSYNC scripts/other/extlinux.conf /mnt/loop/boot/extlinux &&

$CHOWN -R 0:0 /mnt/loop &&

extlinux --install /mnt/loop/boot/extlinux &&

$UMOUNT /mnt/loop &&
partx -d $LOOP &&
losetup -d $LOOP
