#!/usr/bin/dash -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

. $SCRD/genome &&
. $SCRD/species &&

. $SCRD/cross/variables &&
. $XSCR/prepare &&

$SCRD/log $XLOG $XSCR/envenomate &&

. $XSCR/configure &&
. $XSCR/strip
