#!/usr/bin/dash -e

# Copyright (c) 2019, Firas Khalil Khana
# Distributed under the terms of the ISC License

. $TSCR/native/variables
. $TSCR/native/prepare
. $TSCR/native/log

. $TSCR/native/fetch
. $TSCR/native/verify

(. $TSCR/native/construct | tee $NLOG/$log/out.log) 3>&1 1>&2 2>&3 | tee \
  $NLOG/$log/err.log
