colorscheme slate
filetype plugin indent on
set autoindent
set colorcolumn=80
set cursorcolumn
set cursorline
set expandtab
set hlsearch
set incsearch
set lazyredraw
set modifiable
set mouse=a
set number
set relativenumber
set shiftwidth=2
set smarttab
set softtabstop=0
set t_Co=256
set tabstop=2
syntax on
