#!/bin/sh -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

sudo \
  chroot $GLAD \
    $TLCD/bin/env -i \
    HOME=/root \
    PATH=/usr/bin/ccache:/usr/bin:/bin:$TLCD/bin/ccache:$TLCD/bin \
    TERM=xterm-256color \
    PS1='[\[\033[0;44m\]glaucus\[\033[0m\]:\[\033[1m\]\w\[\033[0m\]]$ ' \
    oksh
