#!/bin/sh -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

. $SCRD/genome &&
. $SCRD/species &&

. $SCRD/chroot/variables &&
. $CSCR/check &&
. $CSCR/prepare &&

$SCRD/log $CLOG $CSCR/construct &&

. $CSCR/strip &&
. $CSCR/backup &&
. $CSCR/root &&
. $CSCR/vkfs &&
. $CSCR/resolv &&

. $SCRD/cross/check &&

. $CSCR/enter
