#!/usr/bin/dash -eux

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

. $SCRD/chroot/variables &&
. $CSCR/check &&
. $CSCR/prepare &&

. $SCRD/genome &&
. $SCRD/species &&

$SCRD/log $CLOG $CSCR/construct &&

. $CSCR/strip &&
. $CSCR/backup &&
. $CSCR/root &&
. $CSCR/vkfs &&
. $CSCR/resolv &&

. $SCRD/system/check &&

. $CSCR/enter
