#!/usr/bin/dash -eux

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

. scripts/chroot/variables &&
. $CSCR/check &&
. $CSCR/prepare &&

$SCRD/log $CLOG $CSCR/construct &&

. $CSCR/clean &&
. $CSCR/backup &&
. $CSCR/root &&
. $CSCR/vkfs &&
. $CSCR/resolv &&

. $SCRD/system/check &&

. $CSCR/chroot
