#!/usr/bin/dash -eux

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

CHOWN="chown -R" &&
LN="ln -fns" &&
MKDIR="install -d" &&
RM="rm -fr" &&
RSYNC="rsync -aHAXx" &&
UMOUNT="umount -fqR" &&

NAME=glaucus.img &&
SIZE=128M &&
LOOP=$(losetup -f) &&

$RM $NAME &&
qemu-img create -f raw $NAME $SIZE &&
dd if=scripts/other/mbr.bin of=$NAME conv=notrunc bs=440 count=1 &&

parted -s $NAME mklabel msdos &&
parted -s -a none $NAME mkpart primary ext4 0 $SIZE &&
parted -s -a none $NAME set 1 boot on &&

losetup -D &&
losetup $LOOP $NAME &&

partx -a $LOOP &&
mkfs.ext4 $(printf $LOOP)p1 &&

mount $(printf $LOOP)p1 /mnt/loop &&

$RM /mnt/loop/lost+found &&

$MKDIR /mnt/loop/dev &&
$MKDIR /mnt/loop/proc &&
$MKDIR /mnt/loop/run &&
$MKDIR /mnt/loop/sys &&

$MKDIR -m 0750 /mnt/loop/root &&
$MKDIR -m 1777 /mnt/loop/tmp &&

$RSYNC system/boot /mnt/loop &&
$RSYNC system/etc /mnt/loop &&
$RSYNC system/usr /mnt/loop &&
$RSYNC system/var /mnt/loop &&

$LN usr/bin /mnt/loop/bin &&
$LN usr/lib /mnt/loop/lib &&

$MKDIR /mnt/loop/boot/extlinux &&
$RSYNC scripts/other/extlinux.conf /mnt/loop/boot/extlinux &&
$CHOWN 0:0 /mnt/loop/boot/extlinux/extlinux.conf &&
extlinux --install /mnt/loop/boot/extlinux &&

$UMOUNT /mnt/loop &&
partx -d $LOOP &&
losetup -d $LOOP
