#!/usr/bin/dash -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

. $SCRD/genome &&
. $SCRD/species &&

. $SCRD/system/variables &&
. $SSCR/prepare &&

$SCRD/log $SLOG $SSCR/envenomate &&

. $SSCR/configure &&
. $SSCR/strip
