#!/toolchain/bin/dash -eux

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

. $SCRD/system/variables &&
. $SSCR/prepare &&

. $SCRD/genome &&
. $SCRD/species &&

$SCRD/log $SLOG $SSCR/construct &&

. $SSCR/adjust &&

$SCRD/log $SLOG $SSCR/envenomate &&

. $SSCR/configure &&
. $SSCR/strip
