#!/usr/bin/dash -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

. $CERD/$1/ceras &&

$SCRD/contact "$nom $ver" &&

$SCRD/contact check &&
if [ ! -d $SRCD/$nom ]; then
  $MKDIR $SRCD/$nom &&

  . $SCRD/fetch ||
  $SCRD/die ceras $nom fetch $? ||
  exit
else
  . $SCRD/verify &&
  $SCRD/contact
fi
