#!/usr/bin/dash -eux

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

$MKDIR $SCER/$1/sac &&
$MKDIR $SCER/$1/venom &&

$SCRD/construct system $1 &&

$RSYNC $SCER/$1/sac/ /
