#!/usr/bin/dash -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

$MKDIR $XCER/$1/sac &&
$MKDIR $XCER/$1/venom &&

$SCRD/construct cross $1 &&

$RSYNC $XCER/$1/sac/ $CRSD
