#!/usr/bin/dash -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

$MKDIR $BAKD &&
$MKDIR $SRCD &&
$MKDIR $TLCD &&

$MKDIR $LOGD/chroot &&
$MKDIR $LOGD/system &&
$MKDIR $LOGD/toolchain/cross &&
$MKDIR $LOGD/toolchain/native &&

$MKDIR $TMPD/chroot/builds &&
$MKDIR $TMPD/chroot/sources &&

$MKDIR $TMPD/system/builds &&
$MKDIR $TMPD/system/cerata &&
$MKDIR $TMPD/system/sources &&

$MKDIR $TMPD/toolchain/sources &&
$MKDIR $TMPD/toolchain/cross/builds &&
$MKDIR $TMPD/toolchain/native/builds
