#!/bin/sh -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

$MKDIR $BAKD &&
$MKDIR $SRCD &&
$MKDIR $TLCD &&

$MKDIR $LOGD/chroot &&
$MKDIR $LOGD/cross &&
$MKDIR $LOGD/toolchain &&

$MKDIR $TMPD/chroot/builds &&
$MKDIR $TMPD/chroot/sources &&

$MKDIR $TMPD/cross/builds &&
$MKDIR $TMPD/cross/cerata &&
$MKDIR $TMPD/cross/sources &&

$MKDIR $TMPD/toolchain/sources &&
$MKDIR $TMPD/toolchain/builds
