#!/bin/sh -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

export FLOG=$1 &&

$MKDIR $FLOG &&

. $2 ||
printf "$?\n" > $FLOG/status &&

[ -e $FLOG/status ] &&
exit $(cat $FLOG/status) ||
exit 0
